# Archivo docker/apache-config.conf
ServerName localhost

# Habilitar módulos necesarios
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

# Configurar el directorio donde están los archivos PHP
DocumentRoot /var/www/html

<Directory "/var/www/html">
    AllowOverride All
    Require all granted
</Directory>

# Pasar las solicitudes de archivos PHP a PHP-FPM
<FilesMatch \.php$>
    SetHandler "proxy:fcgi://wheelz_php:9000"
</FilesMatch>